### ISSUE TITLE
卡在某一题

### ISSUE THREAD

**Issue by dolajiang** [zsmlqlj/hlju-mapleT.A#1]
会出现卡在某题，而无法继续的情况。特别是会出现在第一次没刷完，第二次接着刷的时候。

**Comment by zsmlqlj** [comment]
问题已收到，会尽快解决。
顺便问一下，你的环境配置没问题吧？selenium和相应chrome版本的chrome driver都是必要的

**Comment by zsmlqlj** [comment]
这个问题我有印象，大概是因为答案页面加载过快/题目加载过慢，读取的text格式与题目格式不同，会出现匹配失败的情况，是否问题出现在选择题中？

当时我应该已经改过了正则表达式的匹配标准，如果还是不行的话，尝试加长WebDriverWait（timeout=？）的timeout时间，有很大可能是因为临近截止，上机人数过多而浏览器页面加载每一题过慢，没有读到相应内容就进行后续操作导致的。

之后会对这个比较隐蔽的问题做单独处理

**Comment by dolajiang** [comment]
1.环境配置应该没有问题，chorme版本正确
2.这个问题曾经出现在选择题中
3.第一次使用时，都可以一次性刷完，但如果刷到一半终止，之后不管尝试几遍都会卡死
4.希望作者开发出可以刷指定章节的功能[旺柴]
5.我去试试几个操作

**Comment by zsmlqlj** [comment]
关于再启动导致卡死问题我这边尝试了一下，没遇到，我再看一看哈！

指定章节的功能确实需要，会尽快开发~

如果觉得还行可以点一下小小的star或者分享给同学，也欢迎大佬建立新分支来完善这个脚本，说到底是为了写这个脚本才学的python，所以比较基础哈哈

目前在开发android平台的刷学习通app，只需要学号密码即可登录，当然也有课表，查考试，查成绩等等教务处的常用功能！进度已经70%左右，完成后也会完全免费开源到github上，敬请期待~

没有其他问题的话就可以关闭comment啦
